version: "3.8"

services:
  omopdb:
    image: postgres:16
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./omopdb/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./omopdb/postgresql.conf:/etc/postgresql/postgresql.conf
      - omop-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ohdsi
      OHDSI_ADMIN_PASSWORD: ${OHDSI_ADMIN_PASSWORD:?}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    shm_size: 1g
    ports:
      - "${PGPORT:-5432}:5432"
    networks:
      - ohdsi-omop-v5

  webapi:
    image: ohdsi/webapi:2.14.0
    restart: unless-stopped
    ports:
      - "${WEBAPI_HOST_PORT:-9876}:8080"
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      DATASOURCE_USERNAME: ohdsi_admin_user
      DATASOURCE_PASSWORD: ${OHDSI_ADMIN_PASSWORD:?}
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: ohdsi_admin_user
      FLYWAY_DATASOURCE_PASSWORD: ${OHDSI_ADMIN_PASSWORD:?}
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi

      SECURITY_ORIGIN: "http://localhost:8080"
      SECURITY_CORS_ENABLED: "true"
      SECURITY_SSL_ENABLED: "false"

    networks:
      - ohdsi-omop-v5

  atlas:
    image: ohdsi/atlas:2.14.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config-local.js:/etc/atlas/config-local.js
    networks:
      - ohdsi-omop-v5

networks:
  ohdsi-omop-v5:
    name: ${DOCKER_NETWORK}

volumes:
  omop-postgres-data:
    name: omop-postgres-data
    driver: local